/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as KurserRouteImport } from './routes/kurser'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as HandledarsamtalRouteImport } from './routes/handledarsamtal'
import { Route as DelmalRouteImport } from './routes/delmal'
import { Route as AnsokanRouteImport } from './routes/ansokan'
import { Route as IndexRouteImport } from './routes/index'

const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KurserRoute = KurserRouteImport.update({
  id: '/kurser',
  path: '/kurser',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const HandledarsamtalRoute = HandledarsamtalRouteImport.update({
  id: '/handledarsamtal',
  path: '/handledarsamtal',
  getParentRoute: () => rootRouteImport,
} as any)
const DelmalRoute = DelmalRouteImport.update({
  id: '/delmal',
  path: '/delmal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsokanRoute = AnsokanRouteImport.update({
  id: '/ansokan',
  path: '/ansokan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ansokan': typeof AnsokanRoute
  '/delmal': typeof DelmalRoute
  '/handledarsamtal': typeof HandledarsamtalRoute
  '/installningar': typeof InstallningarRoute
  '/kurser': typeof KurserRoute
  '/profil': typeof ProfilRoute
  '/schema': typeof SchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ansokan': typeof AnsokanRoute
  '/delmal': typeof DelmalRoute
  '/handledarsamtal': typeof HandledarsamtalRoute
  '/installningar': typeof InstallningarRoute
  '/kurser': typeof KurserRoute
  '/profil': typeof ProfilRoute
  '/schema': typeof SchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ansokan': typeof AnsokanRoute
  '/delmal': typeof DelmalRoute
  '/handledarsamtal': typeof HandledarsamtalRoute
  '/installningar': typeof InstallningarRoute
  '/kurser': typeof KurserRoute
  '/profil': typeof ProfilRoute
  '/schema': typeof SchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ansokan'
    | '/delmal'
    | '/handledarsamtal'
    | '/installningar'
    | '/kurser'
    | '/profil'
    | '/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ansokan'
    | '/delmal'
    | '/handledarsamtal'
    | '/installningar'
    | '/kurser'
    | '/profil'
    | '/schema'
  id:
    | '__root__'
    | '/'
    | '/ansokan'
    | '/delmal'
    | '/handledarsamtal'
    | '/installningar'
    | '/kurser'
    | '/profil'
    | '/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnsokanRoute: typeof AnsokanRoute
  DelmalRoute: typeof DelmalRoute
  HandledarsamtalRoute: typeof HandledarsamtalRoute
  InstallningarRoute: typeof InstallningarRoute
  KurserRoute: typeof KurserRoute
  ProfilRoute: typeof ProfilRoute
  SchemaRoute: typeof SchemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurser': {
      id: '/kurser'
      path: '/kurser'
      fullPath: '/kurser'
      preLoaderRoute: typeof KurserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handledarsamtal': {
      id: '/handledarsamtal'
      path: '/handledarsamtal'
      fullPath: '/handledarsamtal'
      preLoaderRoute: typeof HandledarsamtalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delmal': {
      id: '/delmal'
      path: '/delmal'
      fullPath: '/delmal'
      preLoaderRoute: typeof DelmalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ansokan': {
      id: '/ansokan'
      path: '/ansokan'
      fullPath: '/ansokan'
      preLoaderRoute: typeof AnsokanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnsokanRoute: AnsokanRoute,
  DelmalRoute: DelmalRoute,
  HandledarsamtalRoute: HandledarsamtalRoute,
  InstallningarRoute: InstallningarRoute,
  KurserRoute: KurserRoute,
  ProfilRoute: ProfilRoute,
  SchemaRoute: SchemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
